name = "TacMetrics"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CommunityDetection = "d427f087-d71a-5a1b-ace0-b93392eea9ff"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
Parquet2 = "98572fba-bba0-415d-956f-fa77e587d26d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
SymbolServer = "cf896787-08d5-524d-9de7-132aaa0cb996"
