[project]
name = "tacmetrics"
version = "0.1.0"
description = "Metrics of Tactical FPS Game from Data and Stats"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "awpy>=2.0.2",
    "demoparser2>=0.40.0",
]
